version: '2'

services:
  documentStore:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    container_name: documentStore
  cacheStore:
    image: redis:alpine
    container_name: cacheStore
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  mongo-data:
    external: true
  redis-data:
    external: true
